
CREATE TABLE appointment_statuses (
    appointment_status_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(20) NOT NULL,
    CONSTRAINT pk_appointment_status PRIMARY KEY (appointment_status_id)
);

CREATE TABLE document_types (
    doc_type_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(20) NOT NULL,
    CONSTRAINT pk_document_types PRIMARY KEY (doc_type_id)
);

CREATE TABLE positions (
    position_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(100),
    CONSTRAINT pk_positions PRIMARY KEY (position_id)
);

CREATE TABLE record_types (
    record_type_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(50) NOT NULL,
    CONSTRAINT pk_record_types PRIMARY KEY (record_type_id)
);

CREATE TABLE roles (
    role_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(50) NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (role_id),
    CONSTRAINT uq_roles_name UNIQUE (name)
);

CREATE TABLE specialties (
    specialty_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(100),
    CONSTRAINT pk_specialties PRIMARY KEY (specialty_id)
);

CREATE TABLE users (
    user_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_name varchar(50) NOT NULL,
    password_hash varchar(255) NOT NULL,
    email varchar(100),
    phone varchar(20),
    is_active boolean DEFAULT true,
    create_date timestamp DEFAULT CURRENT_TIMESTAMP,
    edit_date timestamp,
    create_user integer,
    edit_user integer,
    CONSTRAINT pk_users PRIMARY KEY (user_id),
    CONSTRAINT uq_users_user_name UNIQUE (user_name)
);

CREATE TABLE patients (
    patient_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    doc_num varchar(30),
    address varchar(300),
    first_name1 varchar(50) NOT NULL,
    first_name2 varchar(50),
    last_name1 varchar(50) NOT NULL,
    last_name2 varchar(50),
    doc_type_id integer,
    birth_date date,
    sex smallint NOT NULL DEFAULT 0,
    tel1 varchar(20),
    tel2 varchar(20),
    mobile1 varchar(20),
    mobile2 varchar(20),
    email varchar(100),
    observation varchar(1025),
    status boolean DEFAULT true,
    create_user integer,
    create_date timestamp DEFAULT CURRENT_TIMESTAMP,
    edit_user integer,
    edit_date timestamp,
    CONSTRAINT pk_patients PRIMARY KEY (patient_id)
);

CREATE TABLE employees (
    employee_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id integer NOT NULL,
    doc_num varchar(30) NOT NULL,
    address varchar(300),
    first_name1 varchar(50) NOT NULL,
    first_name2 varchar(50),
    last_name1 varchar(50) NOT NULL,
    last_name2 varchar(50),
    doc_type_id integer,
    birth_date date,
    sex smallint NOT NULL DEFAULT 0,
    tel1 varchar(20),
    tel2 varchar(20),
    mobile1 varchar(20),
    mobile2 varchar(20),
    email varchar(100),
    observation varchar(1025),
    status boolean DEFAULT true,
    create_user integer,
    create_date timestamp DEFAULT CURRENT_TIMESTAMP,
    edit_user integer,
    edit_date timestamp,
    CONSTRAINT pk_employees PRIMARY KEY (employee_id),
    CONSTRAINT uq_employees_doc_num UNIQUE (doc_num)
);

CREATE TABLE appointments (
    appointment_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    patient_id integer NOT NULL,
    employee_id integer NOT NULL,
    appointment_date_time timestamp,
    appointment_status_id integer DEFAULT 1,
    observation varchar(1025),
    description varchar(1025),
    amount numeric(16,4),
    create_user integer,
    create_date timestamp DEFAULT CURRENT_TIMESTAMP,
    edit_user integer,
    edit_date timestamp,
    CONSTRAINT pk_appointments PRIMARY KEY (appointment_id)
);

CREATE TABLE medical_records (
    medical_record_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    appointment_id integer NOT NULL,
    chief_complaint text,
    diagnosis text,
    treatment text,
    prescription text,
    observation text,
    recommendations text,
    create_user integer,
    create_date timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    edit_user integer,
    edit_date timestamp,
    CONSTRAINT pk_medical_records PRIMARY KEY (medical_record_id),
    CONSTRAINT fk_medical_records_appointments
        FOREIGN KEY (appointment_id)
        REFERENCES appointments (appointment_id)
);

CREATE TABLE employee_positions (
    employee_id integer NOT NULL,
    position_id integer NOT NULL,
    create_user integer,
    create_date timestamp DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_employee_positions PRIMARY KEY (employee_id, position_id)
);

CREATE TABLE employee_specialties (
    employee_id integer NOT NULL,
    specialty_id integer NOT NULL,
    create_user integer NOT NULL,
    create_date timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_employee_specialties PRIMARY KEY (employee_id, specialty_id)
);

CREATE TABLE user_roles (
    user_id integer NOT NULL,
    role_id integer NOT NULL,
    create_user integer,
    create_date timestamp DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role_id)
);

ALTER TABLE appointments
    ADD CONSTRAINT fk_appointments_status
    FOREIGN KEY (appointment_status_id)
    REFERENCES appointment_statuses (appointment_status_id);

ALTER TABLE appointments
    ADD CONSTRAINT fk_appointments_create_user
    FOREIGN KEY (create_user)
    REFERENCES users (user_id);

ALTER TABLE appointments
    ADD CONSTRAINT fk_appointments_edit_user
    FOREIGN KEY (edit_user)
    REFERENCES users (user_id);

ALTER TABLE appointments
    ADD CONSTRAINT fk_appointments_employee
    FOREIGN KEY (employee_id)
    REFERENCES employees (employee_id);

ALTER TABLE appointments
    ADD CONSTRAINT fk_appointments_patient
    FOREIGN KEY (patient_id)
    REFERENCES patients (patient_id);

ALTER TABLE employee_positions
    ADD CONSTRAINT fk_employee_positions_employee
    FOREIGN KEY (employee_id)
    REFERENCES employees (employee_id);

ALTER TABLE employee_positions
    ADD CONSTRAINT fk_employee_positions_position
    FOREIGN KEY (position_id)
    REFERENCES positions (position_id);

ALTER TABLE employee_specialties
    ADD CONSTRAINT fk_employee_specialties_employee
    FOREIGN KEY (employee_id)
    REFERENCES employees (employee_id);

ALTER TABLE employee_specialties
    ADD CONSTRAINT fk_employee_specialties_specialty
    FOREIGN KEY (specialty_id)
    REFERENCES specialties (specialty_id);

ALTER TABLE employee_specialties
    ADD CONSTRAINT fk_employee_specialties_create_user
    FOREIGN KEY (create_user)
    REFERENCES users (user_id);

ALTER TABLE employees
    ADD CONSTRAINT fk_employees_user
    FOREIGN KEY (user_id)
    REFERENCES users (user_id);

ALTER TABLE employees
    ADD CONSTRAINT fk_employees_doc_type
    FOREIGN KEY (doc_type_id)
    REFERENCES document_types (doc_type_id);

ALTER TABLE employees
    ADD CONSTRAINT fk_employees_create_user
    FOREIGN KEY (create_user)
    REFERENCES users (user_id);

ALTER TABLE employees
    ADD CONSTRAINT fk_employees_edit_user
    FOREIGN KEY (edit_user)
    REFERENCES users (user_id);

ALTER TABLE patients
    ADD CONSTRAINT fk_patients_doc_type
    FOREIGN KEY (doc_type_id)
    REFERENCES document_types (doc_type_id);

ALTER TABLE patients
    ADD CONSTRAINT fk_patients_create_user
    FOREIGN KEY (create_user)
    REFERENCES users (user_id);

ALTER TABLE patients
    ADD CONSTRAINT fk_patients_edit_user
    FOREIGN KEY (edit_user)
    REFERENCES users (user_id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_user_roles_user
    FOREIGN KEY (user_id)
    REFERENCES users (user_id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_user_roles_role
    FOREIGN KEY (role_id)
    REFERENCES roles (role_id);

ALTER TABLE medical_records
    ADD CONSTRAINT uq_medical_records_appointment
    UNIQUE (appointment_id);

ALTER TABLE medical_records
    ADD CONSTRAINT fk_medical_records_create_user
    FOREIGN KEY (create_user)
    REFERENCES users (user_id);	


ALTER TABLE medical_records
    ALTER COLUMN create_user SET NOT NULL;

ALTER TABLE medical_records
    ADD CONSTRAINT fk_medical_records_edit_user
    FOREIGN KEY (edit_user)
    REFERENCES users (user_id);

/******************/

ALTER TABLE users
    ALTER COLUMN create_user SET NOT NULL;

ALTER TABLE users
    ADD CONSTRAINT fk_users_create_user
    FOREIGN KEY (create_user)
    REFERENCES users (user_id);

ALTER TABLE users
    ADD CONSTRAINT fk_users_edit_user
    FOREIGN KEY (edit_user)
    REFERENCES users (user_id);
/*************************/

ALTER TABLE appointments
    ALTER COLUMN create_user SET NOT NULL;

ALTER TABLE patients
    ALTER COLUMN create_user SET NOT NULL;

ALTER TABLE employees
    ALTER COLUMN create_user SET NOT NULL;	

ALTER TABLE medical_records
    ALTER COLUMN create_user SET NOT NULL;	

/***********************/

ALTER TABLE employee_positions
    ADD CONSTRAINT fk_employee_positions_create_user
    FOREIGN KEY (create_user)
    REFERENCES users (user_id);	

/*******************/

ALTER TABLE employees
ADD CONSTRAINT uq_employees_user_id UNIQUE (user_id);


/*****************************/

ALTER TABLE user_roles
    ALTER COLUMN create_user SET NOT NULL;

ALTER TABLE user_roles
    ADD CONSTRAINT fk_user_roles_create_user
    FOREIGN KEY (create_user)
    REFERENCES users (user_id);

/**********/

ALTER TABLE appointment_statuses
ADD CONSTRAINT uq_appointment_statuses_name UNIQUE (name);

/*************************/

ALTER TABLE document_types
ADD CONSTRAINT uq_document_types_name UNIQUE (name);

ALTER TABLE positions
ADD CONSTRAINT uq_positions_name UNIQUE (name);

ALTER TABLE record_types
ADD CONSTRAINT uq_record_types_name UNIQUE (name);

ALTER TABLE Specialties
ADD CONSTRAINT uq_sspecialties_name UNIQUE (name);






	

	
	