--
-- PostgreSQL database dump
--

\restrict 6A5Cj1pjfOAP9BAdeWCG9yM0zJRR2GDKMY7lKe02GgSEhso2zPso1X7oXhyWJ6T

-- Dumped from database version 18.6
-- Dumped by pg_dump version 18.6

-- Started on 2026-08-27 10:37:58

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 244 (class 1255 OID 24627)
-- Name: set_edit_date(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.set_edit_date() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.edit_date = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 243 (class 1259 OID 24577)
-- Name: appointment_statuses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.appointment_statuses (
    appointment_status_id integer NOT NULL,
    name character varying(20) NOT NULL
);


--
-- TOC entry 242 (class 1259 OID 24576)
-- Name: appointment_statuses_appointment_status_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.appointment_statuses ALTER COLUMN appointment_status_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.appointment_statuses_appointment_status_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 236 (class 1259 OID 16731)
-- Name: appointments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.appointments (
    appointment_id integer NOT NULL,
    patient_id integer NOT NULL,
    employee_id integer NOT NULL,
    appointment_date_time timestamp without time zone,
    appointment_status_id integer DEFAULT 1,
    observation character varying(1025),
    description character varying(1025),
    amount numeric(16,4),
    create_user integer NOT NULL,
    create_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    edit_user integer,
    edit_date timestamp without time zone
);


--
-- TOC entry 235 (class 1259 OID 16730)
-- Name: appointments_appointment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.appointments ALTER COLUMN appointment_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.appointments_appointment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16644)
-- Name: document_types; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.document_types (
    doc_type_id integer NOT NULL,
    name character varying(20) NOT NULL
);


--
-- TOC entry 219 (class 1259 OID 16643)
-- Name: document_types_doc_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.document_types ALTER COLUMN doc_type_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.document_types_doc_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 239 (class 1259 OID 16760)
-- Name: employee_positions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.employee_positions (
    employee_id integer NOT NULL,
    position_id integer NOT NULL,
    create_user integer,
    create_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- TOC entry 240 (class 1259 OID 16768)
-- Name: employee_specialties; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.employee_specialties (
    employee_id integer NOT NULL,
    specialty_id integer NOT NULL,
    create_user integer NOT NULL,
    create_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- TOC entry 234 (class 1259 OID 16712)
-- Name: employees; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.employees (
    employee_id integer NOT NULL,
    user_id integer NOT NULL,
    doc_num character varying(30) NOT NULL,
    address character varying(300),
    first_name1 character varying(50) NOT NULL,
    first_name2 character varying(50),
    last_name1 character varying(50) NOT NULL,
    last_name2 character varying(50),
    doc_type_id integer,
    birth_date date,
    sex smallint DEFAULT 0 NOT NULL,
    tel1 character varying(20),
    tel2 character varying(20),
    mobile1 character varying(20),
    mobile2 character varying(20),
    email character varying(100),
    observation character varying(1025),
    status boolean DEFAULT true,
    create_user integer NOT NULL,
    create_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    edit_user integer,
    edit_date timestamp without time zone
);


--
-- TOC entry 233 (class 1259 OID 16711)
-- Name: employees_employee_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.employees ALTER COLUMN employee_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employees_employee_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 238 (class 1259 OID 16744)
-- Name: medical_records; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.medical_records (
    medical_record_id integer NOT NULL,
    appointment_id integer NOT NULL,
    chief_complaint text,
    diagnosis text,
    treatment text,
    prescription text,
    observation text,
    recommendations text,
    create_user integer NOT NULL,
    create_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    edit_user integer,
    edit_date timestamp without time zone
);


--
-- TOC entry 237 (class 1259 OID 16743)
-- Name: medical_records_medical_record_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.medical_records ALTER COLUMN medical_record_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.medical_records_medical_record_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 16697)
-- Name: patients; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.patients (
    patient_id integer NOT NULL,
    doc_num character varying(30),
    address character varying(300),
    first_name1 character varying(50) NOT NULL,
    first_name2 character varying(50),
    last_name1 character varying(50) NOT NULL,
    last_name2 character varying(50),
    doc_type_id integer,
    birth_date date,
    sex smallint DEFAULT 0 NOT NULL,
    tel1 character varying(20),
    tel2 character varying(20),
    mobile1 character varying(20),
    mobile2 character varying(20),
    email character varying(100),
    observation character varying(1025),
    status boolean DEFAULT true,
    create_user integer NOT NULL,
    create_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    edit_user integer,
    edit_date timestamp without time zone
);


--
-- TOC entry 231 (class 1259 OID 16696)
-- Name: patients_patient_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.patients ALTER COLUMN patient_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.patients_patient_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16652)
-- Name: positions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.positions (
    position_id integer NOT NULL,
    name character varying(100)
);


--
-- TOC entry 221 (class 1259 OID 16651)
-- Name: positions_position_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.positions ALTER COLUMN position_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.positions_position_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16659)
-- Name: record_types; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.record_types (
    record_type_id integer NOT NULL,
    name character varying(50) NOT NULL
);


--
-- TOC entry 223 (class 1259 OID 16658)
-- Name: record_types_record_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.record_types ALTER COLUMN record_type_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.record_types_record_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 16667)
-- Name: roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.roles (
    role_id integer NOT NULL,
    name character varying(50) NOT NULL
);


--
-- TOC entry 225 (class 1259 OID 16666)
-- Name: roles_role_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.roles ALTER COLUMN role_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 16677)
-- Name: specialties; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.specialties (
    specialty_id integer NOT NULL,
    name character varying(100)
);


--
-- TOC entry 227 (class 1259 OID 16676)
-- Name: specialties_specialty_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.specialties ALTER COLUMN specialty_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.specialties_specialty_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 241 (class 1259 OID 16778)
-- Name: user_roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_roles (
    user_id integer NOT NULL,
    role_id integer NOT NULL,
    create_user integer NOT NULL,
    create_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- TOC entry 230 (class 1259 OID 16684)
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    user_id integer NOT NULL,
    user_name character varying(50) NOT NULL,
    password_hash character varying(255) NOT NULL,
    email character varying(100),
    phone character varying(20),
    is_active boolean DEFAULT true,
    create_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    edit_date timestamp without time zone,
    create_user integer NOT NULL,
    edit_user integer
);


--
-- TOC entry 229 (class 1259 OID 16683)
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4978 (class 2606 OID 24583)
-- Name: appointment_statuses pk_appointment_status; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.appointment_statuses
    ADD CONSTRAINT pk_appointment_status PRIMARY KEY (appointment_status_id);


--
-- TOC entry 4966 (class 2606 OID 16742)
-- Name: appointments pk_appointments; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.appointments
    ADD CONSTRAINT pk_appointments PRIMARY KEY (appointment_id);


--
-- TOC entry 4934 (class 2606 OID 16650)
-- Name: document_types pk_document_types; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_types
    ADD CONSTRAINT pk_document_types PRIMARY KEY (doc_type_id);


--
-- TOC entry 4972 (class 2606 OID 16767)
-- Name: employee_positions pk_employee_positions; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employee_positions
    ADD CONSTRAINT pk_employee_positions PRIMARY KEY (employee_id, position_id);


--
-- TOC entry 4974 (class 2606 OID 16777)
-- Name: employee_specialties pk_employee_specialties; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employee_specialties
    ADD CONSTRAINT pk_employee_specialties PRIMARY KEY (employee_id, specialty_id);


--
-- TOC entry 4960 (class 2606 OID 16727)
-- Name: employees pk_employees; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT pk_employees PRIMARY KEY (employee_id);


--
-- TOC entry 4968 (class 2606 OID 16754)
-- Name: medical_records pk_medical_records; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.medical_records
    ADD CONSTRAINT pk_medical_records PRIMARY KEY (medical_record_id);


--
-- TOC entry 4958 (class 2606 OID 16710)
-- Name: patients pk_patients; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.patients
    ADD CONSTRAINT pk_patients PRIMARY KEY (patient_id);


--
-- TOC entry 4938 (class 2606 OID 16657)
-- Name: positions pk_positions; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.positions
    ADD CONSTRAINT pk_positions PRIMARY KEY (position_id);


--
-- TOC entry 4942 (class 2606 OID 16665)
-- Name: record_types pk_record_types; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.record_types
    ADD CONSTRAINT pk_record_types PRIMARY KEY (record_type_id);


--
-- TOC entry 4946 (class 2606 OID 16673)
-- Name: roles pk_roles; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT pk_roles PRIMARY KEY (role_id);


--
-- TOC entry 4950 (class 2606 OID 16682)
-- Name: specialties pk_specialties; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.specialties
    ADD CONSTRAINT pk_specialties PRIMARY KEY (specialty_id);


--
-- TOC entry 4976 (class 2606 OID 16785)
-- Name: user_roles pk_user_roles; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role_id);


--
-- TOC entry 4954 (class 2606 OID 16693)
-- Name: users pk_users; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT pk_users PRIMARY KEY (user_id);


--
-- TOC entry 4980 (class 2606 OID 32771)
-- Name: appointment_statuses uq_appointment_statuses_name; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.appointment_statuses
    ADD CONSTRAINT uq_appointment_statuses_name UNIQUE (name);


--
-- TOC entry 4936 (class 2606 OID 32773)
-- Name: document_types uq_document_types_name; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_types
    ADD CONSTRAINT uq_document_types_name UNIQUE (name);


--
-- TOC entry 4962 (class 2606 OID 16729)
-- Name: employees uq_employees_doc_num; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT uq_employees_doc_num UNIQUE (doc_num);


--
-- TOC entry 4964 (class 2606 OID 32769)
-- Name: employees uq_employees_user_id; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT uq_employees_user_id UNIQUE (user_id);


--
-- TOC entry 4970 (class 2606 OID 24590)
-- Name: medical_records uq_medical_records_appointment; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.medical_records
    ADD CONSTRAINT uq_medical_records_appointment UNIQUE (appointment_id);


--
-- TOC entry 4940 (class 2606 OID 32775)
-- Name: positions uq_positions_name; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.positions
    ADD CONSTRAINT uq_positions_name UNIQUE (name);


--
-- TOC entry 4944 (class 2606 OID 32777)
-- Name: record_types uq_record_types_name; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.record_types
    ADD CONSTRAINT uq_record_types_name UNIQUE (name);


--
-- TOC entry 4948 (class 2606 OID 16675)
-- Name: roles uq_roles_name; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT uq_roles_name UNIQUE (name);


--
-- TOC entry 4952 (class 2606 OID 32779)
-- Name: specialties uq_sspecialties_name; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.specialties
    ADD CONSTRAINT uq_sspecialties_name UNIQUE (name);


--
-- TOC entry 4956 (class 2606 OID 16695)
-- Name: users uq_users_user_name; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uq_users_user_name UNIQUE (user_name);


--
-- TOC entry 5010 (class 2620 OID 24631)
-- Name: appointments trg_appointments_edit_date; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_appointments_edit_date BEFORE UPDATE ON public.appointments FOR EACH ROW EXECUTE FUNCTION public.set_edit_date();


--
-- TOC entry 5009 (class 2620 OID 24630)
-- Name: employees trg_employees_edit_date; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_employees_edit_date BEFORE UPDATE ON public.employees FOR EACH ROW EXECUTE FUNCTION public.set_edit_date();


--
-- TOC entry 5011 (class 2620 OID 24632)
-- Name: medical_records trg_medical_records_edit_date; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_medical_records_edit_date BEFORE UPDATE ON public.medical_records FOR EACH ROW EXECUTE FUNCTION public.set_edit_date();


--
-- TOC entry 5008 (class 2620 OID 24629)
-- Name: patients trg_patients_edit_date; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_patients_edit_date BEFORE UPDATE ON public.patients FOR EACH ROW EXECUTE FUNCTION public.set_edit_date();


--
-- TOC entry 5007 (class 2620 OID 24628)
-- Name: users trg_users_edit_date; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_users_edit_date BEFORE UPDATE ON public.users FOR EACH ROW EXECUTE FUNCTION public.set_edit_date();


--
-- TOC entry 4990 (class 2606 OID 16791)
-- Name: appointments fk_appointments_create_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.appointments
    ADD CONSTRAINT fk_appointments_create_user FOREIGN KEY (create_user) REFERENCES public.users(user_id);


--
-- TOC entry 4991 (class 2606 OID 16796)
-- Name: appointments fk_appointments_edit_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.appointments
    ADD CONSTRAINT fk_appointments_edit_user FOREIGN KEY (edit_user) REFERENCES public.users(user_id);


--
-- TOC entry 4992 (class 2606 OID 16801)
-- Name: appointments fk_appointments_employee; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.appointments
    ADD CONSTRAINT fk_appointments_employee FOREIGN KEY (employee_id) REFERENCES public.employees(employee_id);


--
-- TOC entry 4993 (class 2606 OID 16806)
-- Name: appointments fk_appointments_patient; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.appointments
    ADD CONSTRAINT fk_appointments_patient FOREIGN KEY (patient_id) REFERENCES public.patients(patient_id);


--
-- TOC entry 4994 (class 2606 OID 24584)
-- Name: appointments fk_appointments_status; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.appointments
    ADD CONSTRAINT fk_appointments_status FOREIGN KEY (appointment_status_id) REFERENCES public.appointment_statuses(appointment_status_id);


--
-- TOC entry 4998 (class 2606 OID 24616)
-- Name: employee_positions fk_employee_positions_create_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employee_positions
    ADD CONSTRAINT fk_employee_positions_create_user FOREIGN KEY (create_user) REFERENCES public.users(user_id);


--
-- TOC entry 4999 (class 2606 OID 16811)
-- Name: employee_positions fk_employee_positions_employee; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employee_positions
    ADD CONSTRAINT fk_employee_positions_employee FOREIGN KEY (employee_id) REFERENCES public.employees(employee_id);


--
-- TOC entry 5000 (class 2606 OID 16816)
-- Name: employee_positions fk_employee_positions_position; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employee_positions
    ADD CONSTRAINT fk_employee_positions_position FOREIGN KEY (position_id) REFERENCES public.positions(position_id);


--
-- TOC entry 5001 (class 2606 OID 16831)
-- Name: employee_specialties fk_employee_specialties_create_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employee_specialties
    ADD CONSTRAINT fk_employee_specialties_create_user FOREIGN KEY (create_user) REFERENCES public.users(user_id);


--
-- TOC entry 5002 (class 2606 OID 16821)
-- Name: employee_specialties fk_employee_specialties_employee; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employee_specialties
    ADD CONSTRAINT fk_employee_specialties_employee FOREIGN KEY (employee_id) REFERENCES public.employees(employee_id);


--
-- TOC entry 5003 (class 2606 OID 16826)
-- Name: employee_specialties fk_employee_specialties_specialty; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employee_specialties
    ADD CONSTRAINT fk_employee_specialties_specialty FOREIGN KEY (specialty_id) REFERENCES public.specialties(specialty_id);


--
-- TOC entry 4986 (class 2606 OID 16846)
-- Name: employees fk_employees_create_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT fk_employees_create_user FOREIGN KEY (create_user) REFERENCES public.users(user_id);


--
-- TOC entry 4987 (class 2606 OID 16841)
-- Name: employees fk_employees_doc_type; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT fk_employees_doc_type FOREIGN KEY (doc_type_id) REFERENCES public.document_types(doc_type_id);


--
-- TOC entry 4988 (class 2606 OID 16851)
-- Name: employees fk_employees_edit_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT fk_employees_edit_user FOREIGN KEY (edit_user) REFERENCES public.users(user_id);


--
-- TOC entry 4989 (class 2606 OID 16836)
-- Name: employees fk_employees_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT fk_employees_user FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- TOC entry 4995 (class 2606 OID 16755)
-- Name: medical_records fk_medical_records_appointments; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.medical_records
    ADD CONSTRAINT fk_medical_records_appointments FOREIGN KEY (appointment_id) REFERENCES public.appointments(appointment_id);


--
-- TOC entry 4996 (class 2606 OID 24591)
-- Name: medical_records fk_medical_records_create_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.medical_records
    ADD CONSTRAINT fk_medical_records_create_user FOREIGN KEY (create_user) REFERENCES public.users(user_id);


--
-- TOC entry 4997 (class 2606 OID 24597)
-- Name: medical_records fk_medical_records_edit_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.medical_records
    ADD CONSTRAINT fk_medical_records_edit_user FOREIGN KEY (edit_user) REFERENCES public.users(user_id);


--
-- TOC entry 4983 (class 2606 OID 16861)
-- Name: patients fk_patients_create_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.patients
    ADD CONSTRAINT fk_patients_create_user FOREIGN KEY (create_user) REFERENCES public.users(user_id);


--
-- TOC entry 4984 (class 2606 OID 16856)
-- Name: patients fk_patients_doc_type; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.patients
    ADD CONSTRAINT fk_patients_doc_type FOREIGN KEY (doc_type_id) REFERENCES public.document_types(doc_type_id);


--
-- TOC entry 4985 (class 2606 OID 16866)
-- Name: patients fk_patients_edit_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.patients
    ADD CONSTRAINT fk_patients_edit_user FOREIGN KEY (edit_user) REFERENCES public.users(user_id);


--
-- TOC entry 5004 (class 2606 OID 24622)
-- Name: user_roles fk_user_roles_create_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fk_user_roles_create_user FOREIGN KEY (create_user) REFERENCES public.users(user_id);


--
-- TOC entry 5005 (class 2606 OID 16876)
-- Name: user_roles fk_user_roles_role; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES public.roles(role_id);


--
-- TOC entry 5006 (class 2606 OID 16871)
-- Name: user_roles fk_user_roles_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- TOC entry 4981 (class 2606 OID 24603)
-- Name: users fk_users_create_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fk_users_create_user FOREIGN KEY (create_user) REFERENCES public.users(user_id);


--
-- TOC entry 4982 (class 2606 OID 24608)
-- Name: users fk_users_edit_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fk_users_edit_user FOREIGN KEY (edit_user) REFERENCES public.users(user_id);


-- Completed on 2026-08-27 10:37:59

--
-- PostgreSQL database dump complete
--

\unrestrict 6A5Cj1pjfOAP9BAdeWCG9yM0zJRR2GDKMY7lKe02GgSEhso2zPso1X7oXhyWJ6T

