select * from Users
select * from Appointments
select * from AppointmentStatus
select * from Doctors
select * from DocumentTypes
select * from MedicalRecords
select * from Patients
select * from RecordTypes
select * from roles
select * from UserRoles
