using Microsoft.EntityFrameworkCore;
using ClinicManager.Models;

namespace ClinicManager.Data
{
	public class ClinicManagerDbContext : DbContext
	{
		public ClinicManagerDbContext(DbContextOptions<ClinicManagerDbContext> options)
			: base(options)
		{
		}

		// Additional configurations can be added here based on your relationships

		// Tables
		public DbSet<User> Users { get; set; }
		public DbSet<Role> Roles { get; set; }
		public DbSet<UserRole> UserRoles { get; set; }
		public DbSet<DocumentType> DocumentTypes { get; set; }
		public DbSet<Patient> Patients { get; set; }
		public DbSet<AppointmentStatus> AppointmentStatuses { get; set; }
		public DbSet<Appointment> Appointments { get; set; }
		public DbSet<RecordType> RecordTypes { get; set; }
		public DbSet<MedicalRecord> MedicalRecords { get; set; }
		public DbSet<Specialty> Specialties { get; set; }
		public DbSet<Employee> Employees { get; set; }
		public DbSet<Position> Positions { get; set; }
		public DbSet<EmployeePosition> EmployeePositions { get; set; }
		public DbSet<EmployeeSpecialty> EmployeeSpecialties { get; set; }

		// Here you can configure relationships and composite keys

		protected override void OnModelCreating(ModelBuilder modelBuilder)
		{
			base.OnModelCreating(modelBuilder);

			// Composite keys
			modelBuilder.Entity<UserRole>()
				.HasKey(ur => new { ur.UserId, ur.RoleId });

			modelBuilder.Entity<EmployeeSpecialty>()
				.HasKey(es => new { es.EmployeeId, es.SpecialtyId });

			modelBuilder.Entity<EmployeePosition>()
				.HasKey(ep => new { ep.EmployeeId, ep.PositionId });

			// User - Employee (1:1)
			modelBuilder.Entity<User>()
				.HasOne(u => u.Employee)
				.WithOne(e => e.User)
				.HasForeignKey<Employee>(e => e.UserId);

			modelBuilder.Entity<Appointment>()
				.Property(a => a.AppointmentDateTime)
				.HasColumnType("timestamp without time zone");

			// CreateDate generated by PostgreSQL
			foreach (var entityType in modelBuilder.Model.GetEntityTypes())
			{
				var createDateProperty = entityType.FindProperty("CreateDate");

				if (createDateProperty != null)
				{
					createDateProperty.SetDefaultValueSql("CURRENT_TIMESTAMP");
					createDateProperty.ValueGenerated =
						Microsoft.EntityFrameworkCore.Metadata.ValueGenerated.OnAdd;
				}
			}
		}


		/*protected override void OnModelCreating(ModelBuilder modelBuilder)
		{
			base.OnModelCreating(modelBuilder);

			// Example of a composite key for UserRoles
			modelBuilder.Entity<UserRole>()
				.HasKey(ur => new { ur.UserId, ur.RoleId });


			modelBuilder.Entity<EmployeeSpecialty>()
				 .HasKey(es => new { es.EmployeeId, es.SpecialtyId });

			modelBuilder.Entity<User>()
				.HasOne(u => u.Employee)
				.WithOne(e => e.User)
				.HasForeignKey<Employee>(e => e.UserId);

			modelBuilder.Entity<EmployeePosition>()
				.HasKey(ep => new { ep.EmployeeId, ep.PositionId });

			modelBuilder.Entity<User>()
				.Property(u => u.CreateDate)
				.HasDefaultValueSql("CURRENT_TIMESTAMP")
				.ValueGeneratedOnAdd();


	// Additional configurations can be added here based on your relationships 
}*/
	}
}